tasks:
  - name: Setup Tools
    init: |
      # Install tree utility
      if ! command -v tree &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y tree
      fi

      # Install AWS CLI
      if ! aws --version &> /dev/null; then
        cd /workspace
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm -rf aws awscliv2.zip
      fi

      # Install Terraform
      if ! terraform version &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release; echo $VERSION_CODENAME) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt-get install -y terraform
      fi

      # Install PowerShell
      if ! pwsh --version &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q "https://packages.microsoft.com/config/ubuntu/$(. /etc/os-release; echo $VERSION_ID)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update && sudo apt-get install -y powershell
        rm packages-microsoft-prod.deb
      fi
      
      # Install AWS PowerShell modules
      pwsh -Command "Install-Module -Name AWS.Tools.Installer -Force; Install-AWSToolsModule AWS.Tools.EC2, AWS.Tools.S3 -Force -CleanUp"
    
    command: |
      echo "Versions:"
      aws --version || echo "AWS CLI not found."
      terraform version || echo "Terraform not found."
      pwsh --version || echo "PowerShell not found."
