tasks:
  - name: Install Utilities
    init: |
      # Check for tree utility, install if missing
      if ! command -v tree &> /dev/null; then
        apt-get update && apt-get install -y tree
      fi

  - name: Install AWS CLI
    init: |
      # Check if AWS CLI is installed, install if missing
      if ! aws --version &> /dev/null; then
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
      fi

  - name: Install Terraform CLI
    init: |
      # Check if Terraform is installed, install if missing
      if ! terraform version &> /dev/null; then
        apt-get update && apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release; echo $VERSION_CODENAME) main" | tee /etc/apt/sources.list.d/hashicorp.list
        apt update && apt-get install -y terraform
      fi

  - name: Install PowerShell
    init: |
      # Check if PowerShell is installed, install if missing
      if ! pwsh --version &> /dev/null; then
        apt-get update && apt-get install -y wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/$(. /etc/os-release; echo $VERSION_ID)/packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-get update && apt-get install -y powershell
      fi

  - name: Display Versions
    command: |
      echo "AWS CLI Version:"
      aws --version
      echo "Terraform Version:"
      terraform version
      echo "PowerShell Version:"
      pwsh --version
