tasks:
  - name: Setup and Environment Configuration
    init: |
      set -e  # Exit immediately if a command exits with a non-zero status.

      # Update package lists
      sudo apt-get update

      # Install tree utility
      if ! command -v tree &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y tree
      fi

      # Run installation scripts
      ./bin/aws_cli_install.sh
      ./bin/terraform_cli_install.sh
      ./bin/powershell_install.sh
      ./bin/cdk_install.sh
      ./bin/pulumi_install.sh
      export PATH="$PATH:/home/gitpod/.pulumi/bin"
      ./bin/Kubernetes_install.sh
      ./bin/zsh_install.sh

      # Install additional dependencies
      npm install -g aws-cdk
      pip install -r S3/iac/pulumi/requirements.txt
      bundle install --gemfile=S3/SDK/ruby/Gemfile
      mvn install

    command: |
      set -e  # Exit immediately if a command exits with a non-zero status.

      # Verify installations
      export GITPOD_INIT=1
      ./bin/check_installs.sh
      unset GITPOD_INIT

      # Run tests
      mvn test
      rubocop
      shellcheck S3/bash-scripts/*.sh
      exec zsh -l

vscode:
  extensions:
    - redhat.java
    - rebornix.ruby
    - hashicorp.terraform
    - ms-python.python
