#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

#https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/
STACK_NAME="cfn-s3-simple"
aws cloudformation delete-stack \
--stack-name $STACK_NAMEs