name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use Node.js 20

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Updated to use Node.js 20
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./S3/SDK/java/getstarted  # Ensure Maven runs in the correct directory

    - name: Run unit tests
      run: mvn test
      working-directory: ./S3/SDK/java/getstarted  # Ensure Maven runs in the correct directory

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Lint Ruby code
      run: |
        gem install rubocop
        rubocop

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Lint Shell scripts
      run: shellcheck S3/bash-scripts/*.sh



