name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./S3/SDK/java/getstarted

    - name: Run unit tests
      run: mvn test
      working-directory: ./S3/SDK/java/getstarted

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Lint Ruby code
      run: |
        gem install rubocop
        rubocop S3/SDK/ruby/Gemfile S3/SDK/ruby/s3.rb

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Lint Shell scripts
      run: |
        if ls S3/bash-scripts/*.sh 1> /dev/null 2>&1; then
          shellcheck S3/bash-scripts/*.sh
        else
          echo "No shell scripts found in S3/bash-scripts/"
        fi
