name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Specify the distribution
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run unit tests
      run: mvn test

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Lint Ruby code
      run: |
        gem install rubocop
        rubocop

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Lint Shell scripts
      run: shellcheck S3/bash-scripts/*.sh


